AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

